version: '2.1'
services:
  discovery-server:
    image: ghcr.io/zhanbolat/discovery-server-bcc:latest
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"